# Generated by Django 4.1.4 on 2022-12-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_expired_payments_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired_payments',
            name='pay_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_id_Expired', to='servicios.payment_user'),
        ),
    ]
