# Generated by Django 4.1.4 on 2022-12-29 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0005_alter_servicio_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDeUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.ImageField(upload_to='FotoPerfil')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
