# Generated by Django 4.1.4 on 2022-12-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_perfildeusuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfildeusuario',
            table='PerfilDeUsuario',
        ),
    ]
